{% set version = "2.0.6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-nacho
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/NACHO_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/NACHO/NACHO_{{ version }}.tar.gz
  sha256: 31cd8a2c9d11ea064634ce0aa6ceae7a0ef7cf7f76aafa7235f4fba2b4bc3eec

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-data.table
    - r-ggbeeswarm >=0.6.0
    - r-ggforce >=0.3.1
    - r-ggplot2 >=3.3.0
    - r-ggrepel >=0.8.1
    - r-knitr >=1.25
    - r-rmarkdown >=1.16
    - r-shiny >=1.4.0
    - r-shinywidgets >=0.4.9
  run:
    - r-base
    - r-data.table
    - r-ggbeeswarm >=0.6.0
    - r-ggforce >=0.3.1
    - r-ggplot2 >=3.3.0
    - r-ggrepel >=0.8.1
    - r-knitr >=1.25
    - r-rmarkdown >=1.16
    - r-shiny >=1.4.0
    - r-shinywidgets >=0.4.9

test:
  commands:
    - $R -e "library('NACHO')"           # [not win]
    - "\"%R%\" -e \"library('NACHO')\""  # [win]

about:
  home: https://github.com/mcanouil/NACHO, https://mcanouil.github.io/NACHO
  license: GPL-3.0-only
  summary: NanoString nCounter data are gene expression assays where there is no need for the use of enzymes or amplification protocols and work with fluorescent barcodes (Geiss et al. (2018) <doi:10.1038/nbt1385>). Each barcode is assigned a messenger-RNA/micro-RNA (mRNA/miRNA) which after bonding with its target can be
    counted. As a result each count of a specific barcode represents the presence of its target mRNA/miRNA. 'NACHO' (NAnoString quality Control dasHbOard) is able to analyse the exported NanoString nCounter data and facilitates the user in performing a quality control. 'NACHO' does this by visualising quality control metrics,
    expression of control genes, principal components and sample specific size factors in an interactive web application.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Type: Package
# Package: NACHO
# Title: NanoString Quality Control Dashboard
# Version: 1.0.1
# Authors@R: c(person(given = "Mickael", family = "Canouil", role = c("aut", "cre"), email = "mickael.canouil@cnrs.fr", comment = c(ORCID = "0000-0002-3396-4549")), person(given = "Roderick", family = "Slieker", role = "aut", email = "R.C.Slieker@lumc.nl", comment = c(ORCID = "0000-0003-0961-9152")), person(given = "Gerard", family = "Bouland", role = "aut", email = "G.A.Bouland@lumc.nl"))
# Description: NanoString nCounter data are gene expression assays where there is no need for the use of enzymes or amplification protocols and work with fluorescent barcodes (Geiss et al. (2018) <doi:10.1038/nbt1385>). Each barcode is assigned a messenger-RNA/micro-RNA (mRNA/miRNA) which after bonding with its target can be counted. As a result each count of a specific barcode represents the presence of its target mRNA/miRNA. 'NACHO' (NAnoString quality Control dasHbOard) is able to analyse the exported NanoString nCounter data and facilitates the user in performing a quality control. 'NACHO' does this by visualising quality control metrics, expression of control genes, principal components and sample specific size factors in an interactive web application.
# License: GPL-3
# URL: https://github.com/mcanouil/NACHO, https://mcanouil.github.io/NACHO
# BugReports: https://github.com/mcanouil/NACHO/issues
# Depends: R (>= 3.5.0)
# Imports: cli (>= 1.1.0), crayon (>= 1.3.4), dplyr (>= 0.8.3), ggbeeswarm (>= 0.6.0), ggforce (>= 0.3.1), ggplot2 (>= 3.2.1), ggrepel (>= 0.8.1), knitr (>= 1.25), magrittr (>= 1.5), purrr (>= 0.3.3), rlang (>= 0.1.2), rmarkdown (>= 1.16), rstudioapi (>= 0.10), scales (>= 1.0.0), sessioninfo (>= 1.1.1), shiny (>= 1.4.0), shinyWidgets (>= 0.4.9), tibble (>= 2.1.3), tidyr (>= 1.0.0), utils
# Suggests: Biobase, covr (>= 3.3.2), GEOquery, limma, roxygen2 (>= 7.0.2), testthat (>= 2.2.1)
# VignetteBuilder: knitr
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.1.0
# SystemRequirements: pandoc (>= 1.12.3), pandoc-citeproc
# NeedsCompilation: no
# Packaged: 2020-05-26 15:22:01 UTC; mcanouil
# Author: Mickael Canouil [aut, cre] (<https://orcid.org/0000-0002-3396-4549>), Roderick Slieker [aut] (<https://orcid.org/0000-0003-0961-9152>), Gerard Bouland [aut]
# Maintainer: Mickael Canouil <mickael.canouil@cnrs.fr>
# Repository: CRAN
# Date/Publication: 2020-05-26 22:20:13 UTC
